name:                cohabr
version:             0.1.0.0
github:              "0xd34df00d/cohabr"
license:             BSD3
author:              "Georg Rudoy"
maintainer:          "0xd34df00d@gmail.com"
copyright:           "2019 Georg Rudoy"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Scraper for the Habr.com site and Sohabr replacement web UI
category:            Web

description:         Please see the README on GitHub at <https://github.com/0xd34df00d/cohabr#readme>

dependencies:
- base >= 4.7 && < 5
- async
- beam-core
- beam-postgres
- bytestring
- containers
- data-default
- deepseq
- dom-selector
- either
- ekg
- ekg-core
- exceptions
- extra
- feed
- filepath
- hashable
- html-conduit
- html-entities
- http-client
- http-conduit
- http-types
- interpolate
- microlens
- microlens-th
- mtl
- monad-metrics-extensible
- postgresql-simple
- safe
- stm
- text
- time
- tuple
- tz
- uniplate
- unordered-containers
- xml-conduit

library:
  source-dirs: src

ghc-options:
- -Wall

executables:
  scraper-exe:
    main:                Main.hs
    source-dirs:         app/Scraper
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -with-rtsopts=-T
    dependencies:
    - cohabr
    - fast-logger
    - fixed-timestep
    - optparse-applicative
    - unix

  dboneoff-exe:
    main:                Main.hs
    source-dirs:         app/DbOneOff
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cohabr

tests:
  cohabr-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cohabr
    - hspec
    - http-conduit
