name:                cohabr
version:             0.1.0.0
github:              "0xd34df00d/cohabr"
license:             BSD3
author:              "Georg Rudoy"
maintainer:          "0xd34df00d@gmail.com"
copyright:           "2019 Georg Rudoy"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/0xd34df00d/cohabr#readme>

dependencies:
- base >= 4.7 && < 5
- beam-core
- beam-postgres
- bytestring
- containers
- dom-selector
- either
- feed
- hashable
- html-conduit
- interpolate
- microlens
- microlens-th
- mtl
- postgresql-simple
- text
- time
- tuple
- uniplate
- unordered-containers
- xml-conduit

library:
  source-dirs: src

ghc-options:
- -Wall

executables:
  cohabr-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - async
    - cohabr
    - fixed-timestep
    - http-conduit

tests:
  cohabr-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cohabr
