resolver: lts-14.16
packages:
- .
extra-deps:
- can-i-haz-0.3.1.0
- dom-selector-0.2.0.1
- fixed-timestep-0.2.0.1
- monad-metrics-extensible-0.1.0.0
- github: haskell-beam/beam
  commit: 84cac6dff45921ba51720444fd7d429dfbcebace
  subdirs:
  - beam-core
  - beam-migrate
  - beam-postgres
